# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a73b2be0d1ffb22b41345cb51b2f28d5ea8341e84a641ed2591c990c024344b585121c4103b35c988f1a51c2cc64eb6dec3f040ed7d2a6fa48671f5dcc167d2

test:
  secret_key_base: 6c42c191544a342fda5c7df9dc548999b51732f6947695c627304abbe4311f6d9d217b2fb9a31048b37f5f9b0a69c262999ce931385cb609152b294cadddc45d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
